export const ASYNC_UTILS_MARKER = 'ASYNC_UTILS_MARKER';
export const ASYNC_UTILS_STATE = 'ASYNC_STATE';
export const ASYNC_UTILS_STATE_FOR = 'ASYNC_STATE_FOR';
export const ASYNC_UTILS_STATE_GROUP = 'ASYNC_STATE_GROUP';
export const PENDING = 'ASYNC_UTILS/PENDING';
export const DONE = 'ASYNC_UTILS/DONE';
export const FAILURE = 'ASYNC_UTILS/FAILURE';
